/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatesRouteImport } from './routes/states'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsBorderHoverRouteImport } from './routes/components/border-hover'
import { Route as Cases_studiesEvent_loopIndexRouteImport } from './routes/cases_studies/event_loop/index'

const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBorderHoverRoute = ComponentsBorderHoverRouteImport.update({
  id: '/components/border-hover',
  path: '/components/border-hover',
  getParentRoute: () => rootRouteImport,
} as any)
const Cases_studiesEvent_loopIndexRoute =
  Cases_studiesEvent_loopIndexRouteImport.update({
    id: '/cases_studies/event_loop/',
    path: '/cases_studies/event_loop/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/states': typeof StatesRoute
  '/components/border-hover': typeof ComponentsBorderHoverRoute
  '/cases_studies/event_loop': typeof Cases_studiesEvent_loopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/states': typeof StatesRoute
  '/components/border-hover': typeof ComponentsBorderHoverRoute
  '/cases_studies/event_loop': typeof Cases_studiesEvent_loopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/states': typeof StatesRoute
  '/components/border-hover': typeof ComponentsBorderHoverRoute
  '/cases_studies/event_loop/': typeof Cases_studiesEvent_loopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/states'
    | '/components/border-hover'
    | '/cases_studies/event_loop'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/states' | '/components/border-hover' | '/cases_studies/event_loop'
  id:
    | '__root__'
    | '/'
    | '/states'
    | '/components/border-hover'
    | '/cases_studies/event_loop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatesRoute: typeof StatesRoute
  ComponentsBorderHoverRoute: typeof ComponentsBorderHoverRoute
  Cases_studiesEvent_loopIndexRoute: typeof Cases_studiesEvent_loopIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/border-hover': {
      id: '/components/border-hover'
      path: '/components/border-hover'
      fullPath: '/components/border-hover'
      preLoaderRoute: typeof ComponentsBorderHoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases_studies/event_loop/': {
      id: '/cases_studies/event_loop/'
      path: '/cases_studies/event_loop'
      fullPath: '/cases_studies/event_loop'
      preLoaderRoute: typeof Cases_studiesEvent_loopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatesRoute: StatesRoute,
  ComponentsBorderHoverRoute: ComponentsBorderHoverRoute,
  Cases_studiesEvent_loopIndexRoute: Cases_studiesEvent_loopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
