/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as Cases_studiesIndexRouteImport } from './routes/cases_studies/index'
import { Route as AnimationsIndexRouteImport } from './routes/animations/index'
import { Route as ComponentsBorderHoverRouteImport } from './routes/components/border-hover'
import { Route as ComponentsNav_beauty_hoverIndexRouteImport } from './routes/components/nav_beauty_hover/index'
import { Route as ComponentsLogin_beauty1IndexRouteImport } from './routes/components/login_beauty1/index'
import { Route as ComponentsGraphicCharter1IndexRouteImport } from './routes/components/graphic-charter-1/index'
import { Route as Cases_studiesStatesIndexRouteImport } from './routes/cases_studies/states/index'
import { Route as Cases_studiesEvent_loopIndexRouteImport } from './routes/cases_studies/event_loop/index'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const Cases_studiesIndexRoute = Cases_studiesIndexRouteImport.update({
  id: '/cases_studies/',
  path: '/cases_studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimationsIndexRoute = AnimationsIndexRouteImport.update({
  id: '/animations/',
  path: '/animations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBorderHoverRoute = ComponentsBorderHoverRouteImport.update({
  id: '/components/border-hover',
  path: '/components/border-hover',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNav_beauty_hoverIndexRoute =
  ComponentsNav_beauty_hoverIndexRouteImport.update({
    id: '/components/nav_beauty_hover/',
    path: '/components/nav_beauty_hover/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsLogin_beauty1IndexRoute =
  ComponentsLogin_beauty1IndexRouteImport.update({
    id: '/components/login_beauty1/',
    path: '/components/login_beauty1/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsGraphicCharter1IndexRoute =
  ComponentsGraphicCharter1IndexRouteImport.update({
    id: '/components/graphic-charter-1/',
    path: '/components/graphic-charter-1/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Cases_studiesStatesIndexRoute =
  Cases_studiesStatesIndexRouteImport.update({
    id: '/cases_studies/states/',
    path: '/cases_studies/states/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Cases_studiesEvent_loopIndexRoute =
  Cases_studiesEvent_loopIndexRouteImport.update({
    id: '/cases_studies/event_loop/',
    path: '/cases_studies/event_loop/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/components/border-hover': typeof ComponentsBorderHoverRoute
  '/animations': typeof AnimationsIndexRoute
  '/cases_studies': typeof Cases_studiesIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/cases_studies/event_loop': typeof Cases_studiesEvent_loopIndexRoute
  '/cases_studies/states': typeof Cases_studiesStatesIndexRoute
  '/components/graphic-charter-1': typeof ComponentsGraphicCharter1IndexRoute
  '/components/login_beauty1': typeof ComponentsLogin_beauty1IndexRoute
  '/components/nav_beauty_hover': typeof ComponentsNav_beauty_hoverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/components/border-hover': typeof ComponentsBorderHoverRoute
  '/animations': typeof AnimationsIndexRoute
  '/cases_studies': typeof Cases_studiesIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/cases_studies/event_loop': typeof Cases_studiesEvent_loopIndexRoute
  '/cases_studies/states': typeof Cases_studiesStatesIndexRoute
  '/components/graphic-charter-1': typeof ComponentsGraphicCharter1IndexRoute
  '/components/login_beauty1': typeof ComponentsLogin_beauty1IndexRoute
  '/components/nav_beauty_hover': typeof ComponentsNav_beauty_hoverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/components/border-hover': typeof ComponentsBorderHoverRoute
  '/animations/': typeof AnimationsIndexRoute
  '/cases_studies/': typeof Cases_studiesIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/cases_studies/event_loop/': typeof Cases_studiesEvent_loopIndexRoute
  '/cases_studies/states/': typeof Cases_studiesStatesIndexRoute
  '/components/graphic-charter-1/': typeof ComponentsGraphicCharter1IndexRoute
  '/components/login_beauty1/': typeof ComponentsLogin_beauty1IndexRoute
  '/components/nav_beauty_hover/': typeof ComponentsNav_beauty_hoverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/components/border-hover'
    | '/animations'
    | '/cases_studies'
    | '/components'
    | '/cases_studies/event_loop'
    | '/cases_studies/states'
    | '/components/graphic-charter-1'
    | '/components/login_beauty1'
    | '/components/nav_beauty_hover'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/components/border-hover'
    | '/animations'
    | '/cases_studies'
    | '/components'
    | '/cases_studies/event_loop'
    | '/cases_studies/states'
    | '/components/graphic-charter-1'
    | '/components/login_beauty1'
    | '/components/nav_beauty_hover'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/components/border-hover'
    | '/animations/'
    | '/cases_studies/'
    | '/components/'
    | '/cases_studies/event_loop/'
    | '/cases_studies/states/'
    | '/components/graphic-charter-1/'
    | '/components/login_beauty1/'
    | '/components/nav_beauty_hover/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  ComponentsBorderHoverRoute: typeof ComponentsBorderHoverRoute
  AnimationsIndexRoute: typeof AnimationsIndexRoute
  Cases_studiesIndexRoute: typeof Cases_studiesIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  Cases_studiesEvent_loopIndexRoute: typeof Cases_studiesEvent_loopIndexRoute
  Cases_studiesStatesIndexRoute: typeof Cases_studiesStatesIndexRoute
  ComponentsGraphicCharter1IndexRoute: typeof ComponentsGraphicCharter1IndexRoute
  ComponentsLogin_beauty1IndexRoute: typeof ComponentsLogin_beauty1IndexRoute
  ComponentsNav_beauty_hoverIndexRoute: typeof ComponentsNav_beauty_hoverIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases_studies/': {
      id: '/cases_studies/'
      path: '/cases_studies'
      fullPath: '/cases_studies'
      preLoaderRoute: typeof Cases_studiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animations/': {
      id: '/animations/'
      path: '/animations'
      fullPath: '/animations'
      preLoaderRoute: typeof AnimationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/border-hover': {
      id: '/components/border-hover'
      path: '/components/border-hover'
      fullPath: '/components/border-hover'
      preLoaderRoute: typeof ComponentsBorderHoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/nav_beauty_hover/': {
      id: '/components/nav_beauty_hover/'
      path: '/components/nav_beauty_hover'
      fullPath: '/components/nav_beauty_hover'
      preLoaderRoute: typeof ComponentsNav_beauty_hoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/login_beauty1/': {
      id: '/components/login_beauty1/'
      path: '/components/login_beauty1'
      fullPath: '/components/login_beauty1'
      preLoaderRoute: typeof ComponentsLogin_beauty1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/graphic-charter-1/': {
      id: '/components/graphic-charter-1/'
      path: '/components/graphic-charter-1'
      fullPath: '/components/graphic-charter-1'
      preLoaderRoute: typeof ComponentsGraphicCharter1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases_studies/states/': {
      id: '/cases_studies/states/'
      path: '/cases_studies/states'
      fullPath: '/cases_studies/states'
      preLoaderRoute: typeof Cases_studiesStatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases_studies/event_loop/': {
      id: '/cases_studies/event_loop/'
      path: '/cases_studies/event_loop'
      fullPath: '/cases_studies/event_loop'
      preLoaderRoute: typeof Cases_studiesEvent_loopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  ComponentsBorderHoverRoute: ComponentsBorderHoverRoute,
  AnimationsIndexRoute: AnimationsIndexRoute,
  Cases_studiesIndexRoute: Cases_studiesIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  Cases_studiesEvent_loopIndexRoute: Cases_studiesEvent_loopIndexRoute,
  Cases_studiesStatesIndexRoute: Cases_studiesStatesIndexRoute,
  ComponentsGraphicCharter1IndexRoute: ComponentsGraphicCharter1IndexRoute,
  ComponentsLogin_beauty1IndexRoute: ComponentsLogin_beauty1IndexRoute,
  ComponentsNav_beauty_hoverIndexRoute: ComponentsNav_beauty_hoverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
