export type AnimationData = {
  id: string;
  name: string;
  description: string;
  type: 'shape' | 'text';
  animationClass: string;
  duration: number;
};

export const animationsData: AnimationData[] = [
  // Shape animations
  {
    id: 'fade-in',
    name: 'Fade In',
    description: 'Element fades in from transparent to opaque',
    type: 'shape',
    animationClass: 'animate-[fade-in_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'fade-out',
    name: 'Fade Out',
    description: 'Element fades out from opaque to transparent',
    type: 'shape',
    animationClass: 'animate-[fade-out_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'bounce',
    name: 'Bounce',
    description: 'Element bounces up and down with elastic effect',
    type: 'shape',
    animationClass: 'animate-bounce',
    duration: 1,
  },
  {
    id: 'spin',
    name: 'Spin',
    description: 'Element rotates 360 degrees continuously',
    type: 'shape',
    animationClass: 'animate-spin',
    duration: 1,
  },
  {
    id: 'pulse',
    name: 'Pulse',
    description: 'Element scales up and down rhythmically',
    type: 'shape',
    animationClass: 'animate-pulse',
    duration: 2,
  },
  {
    id: 'ping',
    name: 'Ping',
    description: 'Element creates ripple effect outward',
    type: 'shape',
    animationClass: 'animate-ping',
    duration: 1,
  },
  {
    id: 'slide-in-left',
    name: 'Slide In From Left',
    description: 'Element slides in from the left side',
    type: 'shape',
    animationClass: 'animate-[slide-in-left_2s_ease-out_infinite]',
    duration: 2,
  },
  {
    id: 'slide-in-right',
    name: 'Slide In From Right',
    description: 'Element slides in from the right side',
    type: 'shape',
    animationClass: 'animate-[slide-in-right_2s_ease-out_infinite]',
    duration: 2,
  },
  {
    id: 'slide-in-up',
    name: 'Slide In From Up',
    description: 'Element slides in from the bottom',
    type: 'shape',
    animationClass: 'animate-[slide-in-up_2s_ease-out_infinite]',
    duration: 2,
  },
  {
    id: 'slide-in-down',
    name: 'Slide In From Down',
    description: 'Element slides in from the top',
    type: 'shape',
    animationClass: 'animate-[slide-in-down_2s_ease-out_infinite]',
    duration: 2,
  },
  {
    id: 'scale-up',
    name: 'Scale Up',
    description: 'Element grows from small to large',
    type: 'shape',
    animationClass: 'animate-[scale-up_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'scale-down',
    name: 'Scale Down',
    description: 'Element shrinks from large to small',
    type: 'shape',
    animationClass: 'animate-[scale-down_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'rotate-x',
    name: 'Rotate X',
    description: 'Element rotates around the X axis (3D flip)',
    type: 'shape',
    animationClass: 'animate-[rotateX_3s_ease-in-out_infinite]',
    duration: 3,
  },
  {
    id: 'rotate-y',
    name: 'Rotate Y',
    description: 'Element rotates around the Y axis (3D flip)',
    type: 'shape',
    animationClass: 'animate-[rotateY_3s_ease-in-out_infinite]',
    duration: 3,
  },
  {
    id: 'shake',
    name: 'Shake',
    description: 'Element shakes horizontally like an error',
    type: 'shape',
    animationClass: 'animate-[shake_0.5s_ease-in-out_infinite]',
    duration: 0.5,
  },
  {
    id: 'wiggle',
    name: 'Wiggle',
    description: 'Element wiggles back and forth playfully',
    type: 'shape',
    animationClass: 'animate-[wiggle_1s_ease-in-out_infinite]',
    duration: 1,
  },
  {
    id: 'float',
    name: 'Float',
    description: 'Element floats up and down gently',
    type: 'shape',
    animationClass: 'animate-[float_3s_ease-in-out_infinite]',
    duration: 3,
  },
  {
    id: 'swing',
    name: 'Swing',
    description: 'Element swings like a pendulum',
    type: 'shape',
    animationClass: 'animate-[swing_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'jello',
    name: 'Jello',
    description: 'Element wobbles like jello',
    type: 'shape',
    animationClass: 'animate-[jello_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'rubber-band',
    name: 'Rubber Band',
    description: 'Element stretches and snaps back',
    type: 'shape',
    animationClass: 'animate-[rubber-band_1s_ease-in-out_infinite]',
    duration: 1,
  },
  {
    id: 'heartbeat',
    name: 'Heartbeat',
    description: 'Element pulses like a beating heart',
    type: 'shape',
    animationClass: 'animate-[heart-beat_1.5s_ease-in-out_infinite]',
    duration: 1.5,
  },
  {
    id: 'flip',
    name: 'Flip',
    description: 'Element flips 180 degrees',
    type: 'shape',
    animationClass: 'animate-[flip_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'zoom-in',
    name: 'Zoom In',
    description: 'Element zooms in from center',
    type: 'shape',
    animationClass: 'animate-[zoom-in_2s_ease-out_infinite]',
    duration: 2,
  },
  {
    id: 'zoom-out',
    name: 'Zoom Out',
    description: 'Element zooms out to center',
    type: 'shape',
    animationClass: 'animate-[zoom-out_2s_ease-in_infinite]',
    duration: 2,
  },
  {
    id: 'morph-square-circle',
    name: 'Morph Shape',
    description: 'Shape morphs between square and circle',
    type: 'shape',
    animationClass: 'animate-[morph-shape_3s_ease-in-out_infinite]',
    duration: 3,
  },
  {
    id: 'glow',
    name: 'Glow',
    description: 'Element glows with box shadow animation',
    type: 'shape',
    animationClass: 'animate-[glow_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'color-shift',
    name: 'Color Shift',
    description: 'Element cycles through colors',
    type: 'shape',
    animationClass: 'animate-[color-shift_4s_linear_infinite]',
    duration: 4,
  },
  {
    id: 'blur-in',
    name: 'Blur In',
    description: 'Element transitions from blurred to clear',
    type: 'shape',
    animationClass: 'animate-[blur-in_2s_ease-out_infinite]',
    duration: 2,
  },
  {
    id: 'skew',
    name: 'Skew',
    description: 'Element skews left and right',
    type: 'shape',
    animationClass: 'animate-[skew_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'orbit',
    name: 'Orbit',
    description: 'Element moves in a circular orbit path',
    type: 'shape',
    animationClass: 'animate-[orbit_4s_linear_infinite]',
    duration: 4,
  },

  // Text animations
  {
    id: 'text-typing',
    name: 'Typing Effect',
    description: 'Text appears letter by letter like typing',
    type: 'text',
    animationClass:
      'max-w-fit overflow-hidden whitespace-nowrap border-r-2 border-foreground animate-[typing_3s_steps(18)_infinite,blink-caret_0.75s_step-end_infinite]',
    duration: 3,
  },
  {
    id: 'text-wave',
    name: 'Text Wave',
    description: 'Letters wave up and down sequentially',
    type: 'text',
    animationClass: 'animate-[text-wave_2s_ease-in-out_infinite]',
    duration: 2,
  },
  {
    id: 'text-glitch',
    name: 'Text Glitch',
    description: 'Text has a glitchy digital effect',
    type: 'text',
    animationClass: 'animate-[glitch_0.5s_ease-in-out_infinite]',
    duration: 0.5,
  },
  {
    id: 'text-gradient',
    name: 'Text Gradient Flow',
    description: 'Gradient flows through the text',
    type: 'text',
    animationClass:
      'bg-gradient-to-r from-purple-500 via-pink-500 to-red-500 bg-clip-text text-transparent bg-[length:200%_auto] animate-[gradient-flow_3s_linear_infinite]',
    duration: 3,
  },
  {
    id: 'text-blur-reveal',
    name: 'Text Blur Reveal',
    description: 'Text reveals from blur effect',
    type: 'text',
    animationClass: 'animate-[text-blur-reveal_2s_ease-out_infinite]',
    duration: 2,
  },
];

export const BUTTON_CLASSES = {
  start: 'bg-black text-white hover:bg-black/90',
  pause: 'bg-slate-200 text-zinc-700 hover:bg-slate-200/90',
  stop: 'bg-red-500 text-white hover:bg-red-500/90',
  reset: 'bg-blue-100 text-blue-700',
};
